#!/bin/bash

rm -r build ; mkdir build && cd build && conan install .. --build=missing
if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]
    then cmake .. -G "Unix Makefiles" && cmake –build . && make
else
    cmake .. -G "Visual Studio 16 2019" && cmake –build . && MSBuild.exe R-Type.sln
fi
